# Uygulama Adı ve Port
spring.application.name=fitnessapp
server.port=8099

# === PostgreSQL Datasource Configuration (Docker) ===
spring.datasource.url=jdbc:postgresql://localhost:5432/fitnessapp_db
spring.datasource.username=postgres
# Şifre güncellendi
spring.datasource.password=ZEYD1907

# === JPA / Hibernate Configuration for PostgreSQL ===
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# === Güvenlik Loglama Seviyesi ===
logging.level.org.springframework.security=DEBUG